version: '3.8'

services:
  frontend-dev:
    container_name: frontend-react
    build: 
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/react-app:/app
    ports:
      - '8040:8040'

  backend-dev:
    container_name: backend-laravel
    build: 
      context: ./
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/laravel-app:/var/www/html
  
  mysql_db:
    image: mysql:latest
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: backend-laravel
    ports:
      - 3007:3007
      
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9011:80
    environment:
      - PMA_ARBITRARY=1
    

  web-server:
    container_name: webserver-nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8090:80"
    volumes:
      - ./backend/laravel-app:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-dev
      - mysql_db